branch-defaults:
  default:
    environment: app1-dev
deploy:
  artifact: target/demo-0.0.1-SNAPSHOT.jar
global:
  application_name: app1
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-1
  profile: eb-cli
  sc: null
  workspace_type: Application